name: Build & Artifact
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Show Node & npm versions
        run: node -v && npm -v

      - name: Verify lockfile is up to date
        run: |
          npm install --package-lock-only
          git diff --quiet -- package-lock.json || (echo "::error::package-lock.json n'est pas synchronisé avec package.json. Regénérez le lockfile et re-committez-le."; exit 1)

      - name: Install
        run: npm ci

      - name: Build
        run: |
          if [ -f contentlayer.config.ts ]; then
            npx contentlayer build || true
          fi
          if [ -f package.json ]; then
            npm run build || npm run build:prod || true
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: |
            .next/**
            dist/**
            build/**
            out/**
          if-no-files-found: warn
