name: Build & Artifact
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      # Si on ajoute Contentlayer plus tard
      - name: Build
        run: |
          if [ -f contentlayer.config.ts ]; then
            npx contentlayer build || true
          fi
          if [ -f package.json ]; then
            npm run build || npm run build:prod || true
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: |
            .next/**
            dist/**
            build/**
            out/**
          if-no-files-found: warn
