name: Lockfile Auto-Fix
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  fix:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js from .nvmrc
        if: hashFiles('.nvmrc') != ''
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Use Node.js 20 (fallback)
        if: hashFiles('.nvmrc') == ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Align npm to packageManager version
        run: |
          PM=$(node -p "try { require('./package.json').packageManager } catch (e) { '' }")
          if [[ "$PM" == npm@* ]]; then
            echo "Aligning npm to $PM"
            npm install -g "$PM"
          fi
          npm -v

      - name: Regenerate package-lock.json
        run: npm install --package-lock-only
      - name: Commit lockfile if changed
        run: |
          if ! git diff --quiet -- package-lock.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore(lockfile): sync package-lock.json"
            git push
          fi
