name: Lockfile Fix

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to fix (ex: feature/my-branch ou le nom de ta PR)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  fix-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Regenerate lockfile (no full install)
        run: |
          rm -f package-lock.json
          npm install --package-lock-only

      - name: Commit updated lockfile if changed
        run: |
          if ! git diff --quiet -- package-lock.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore(lockfile): sync package-lock with package.json"
            git push
          else
            echo "Lockfile already up to date."
          fi
